# https://help.github.com/en/actions
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# https://github.com/actions

# https://github.com/micro-os-plus/utils-lists-xpack/actions/workflows/ci.yml
name: CI on Push

on:
  push:
    paths-ignore:
      - '.vscode/**'
      - 'LICENSE'
      - '**.md'
      - '.clang-format'
      - '.gitignore'
      - '.npmignore'
      - '.github/workflows/publish-github-pages.yml'
      - '.github/workflows/test-all.yml'
      - 'tests/scripts/**'
      - '**/README**'
      - 'website/**'
    # This should disable running the workflow on tags, according to the
    # on.<push|pull_request>.<branches|tags> GitHub Actions docs.
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
    branches:
      - '*'

jobs:
  ci-test:
    name: 'CI utils-lists tests'

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        os: [ 'ubuntu-22.04', 'macos-12', 'windows-2022' ]
        # https://nodejs.org/en - use LTS
        node-version: [ '18' ]
        # https://www.npmjs.com/package/xpm
        xpm-version: [ '0.18.0' ]

    steps:
    - name: Checkout
      # https://github.com/actions/checkout/
      uses: actions/checkout@v4
      with:
        fetch-depth: 3

    - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      # https://github.com/actions/setup-node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install xpm@${{ matrix.xpm-version }}
      run: npm install -g xpm@${{ matrix.xpm-version }}

    - name: Show environment
      run: |
        id
        uname -a
        node --version
        npm --version
        xpm --version
        env | sort

    - name: Satisfy project dependencies
      run: |
        xpm install -C tests

    - name: Run test-native-cmake-gcc
      run: |
        xpm install --config native-cmake-gcc-debug -C tests
        xpm install --config native-cmake-gcc-release -C tests
        xpm run test-native-cmake-gcc -C tests

    - name: Run test-native-cmake-clang
      run: |
        xpm install --config native-cmake-clang-debug -C tests
        xpm install --config native-cmake-clang-release -C tests
        xpm run test-native-cmake-clang -C tests

    - name: Run test-qemu-cortex-m0-cmake
      run: |
        xpm install --config qemu-cortex-m0-cmake-gcc-debug -C tests
        xpm install --config qemu-cortex-m0-cmake-gcc-release -C tests
        xpm run test-qemu-cortex-m0-cmake-gcc -C tests

    - name: Run test-qemu-cortex-m7f-cmake
      run: |
        xpm install --config qemu-cortex-m7f-cmake-gcc-debug -C tests
        xpm install --config qemu-cortex-m7f-cmake-gcc-release -C tests
        xpm run test-qemu-cortex-m7f-cmake-gcc -C tests

    - name: Run test-qemu-riscv-rv32imac-cmake
      run: |
        xpm install --config qemu-riscv-rv32imac-cmake-gcc-debug -C tests
        xpm install --config qemu-riscv-rv32imac-cmake-gcc-release -C tests
        xpm run test-qemu-riscv-rv32imac-cmake-gcc -C tests

    - name: Run test-qemu-cortex-m0-meson
      run: |
        xpm install --config qemu-cortex-m0-meson-gcc-debug -C tests
        xpm install --config qemu-cortex-m0-meson-gcc-release -C tests
        xpm run test-qemu-cortex-m0-meson-gcc -C tests

